### PR TITLE
Move to latest

### PR DESCRIPTION
**Pull request by kamilkisiela**
@marktani  But you should check it with working GraphQL endpoint, I just moved things to the latest releases without checking if it works.

### CODE REVIEW

**Comment by marktani** [comment]
Haha awesome. I was just finished with my update to the latest. Thanks, now I can compare to your version :tada:

**Comment by kamilkisiela** [comment]
Oh :) New version of `angular2-apollo` is coming soon, with AoT support!!! I will make your two examples working with Ahead-of-Time compilation soon :fast_forward:

**Comment by marktani** [comment]
Great! I saw you also add batching, nice!

**Comment by kamilkisiela** [comment]
If you have any issue with Angular2 etc, you can take a look at [GitHunt-Angular2](http://github.com/apollostack/GitHunt-angular2). I try to keep it always up to date with everything.

**Comment by marktani** [comment]
instagram-failed

There is an issue that I cannot resolve :(

**Comment by kamilkisiela** [comment]
Will check it, could you pass me the API key, so I can use a prepared GraphQL endpoint?

**Comment by marktani** [comment]
Done in Slack :)

**Comment by kamilkisiela** [comment]
I removed the batching, seems it's not working this way.

**Comment by kamilkisiela** [comment]
Should be fine now

**Comment by marktani** [comment]
awesome, thanks :+1:

**Comment by marktani** [comment]
I found this note in the [Apollo Client docs]:(http://dev.apollodata.com/core/network.html#BatchingExplained)

> Requests to servers that don’t support transport batching will fail.

So that's why it didn't work :slightly_smiling_face:

**Pull request merged**
