### PR TITLE
Latest with update queries

### PR DESCRIPTION
**Pull request by kamilkisiela**
:))

Thanks to this you know what to change / update in other examples

### CODE REVIEW

**Comment by marktani** [comment]
Great! Will check it out tomorrow :fist_oncoming:

**Comment by marktani** [comment]
Hey Kamil, any update regarding this:

> Also, when we'll finish all the work on angular2-apollo I'll update #7 so you guys can keep it open till then?

**Comment by kamilkisiela** [comment]
5th release candidate of `angular2-apollo` should be the last one, so you can just replace it with `0.9.0` in near future. We brought back support for TypeScript 2.0 compiler.

Check it out and let me know if all works :+1:

**Comment by marktani** [comment]
Awesome, will do! :tada:

**Comment by marktani** [comment]
When I try to run, I get this error:

property-does-not-exists

Even though we declare `allPosts` with `any`:

```
export class FeedComponent implements OnInit, OnDestroy {

  loading: boolean = true;
  allPosts: any;
  allPostsSub: Subscription;

```

**Comment by kamilkisiela** [comment]
@marktani about the error

just change `}).subscribe(({data, loading}) => {` to `}).subscribe(({data, loading}: any) => {`, because `data` is a type of `{}` so `data.something` won't work, but `data['something']` will.

**Comment by kamilkisiela** [comment]
@marktani Did few updates and fixed that issue

**Comment by marktani** [comment]
awesome! thanks :)

**Comment by marktani** [comment]
I just got rid of `allPosts.reverse` because with new Apollo versions, `allPosts` is read-only

**Pull request merged**
